---
- name: Ensure OCI Object storage container exists
  command: oci os bucket create --name {{container_name}} --public-access-type ObjectRead
  register: result
  failed_when: result.rc>1

- name: Upload to OCI Object storage
  shell: oci os object bulk-upload -bn  {{ container_name }} --src-dir {{ source_path }} --overwrite --prefix "{{ destination_path }}/"
  async: 3600
  poll: 10
