- hosts: local
  become: yes
  gather_facts: no
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  environment:
        AZURE_STORAGE_ACCOUNT: "{{ sunbird_public_storage_account_name }}"
        AZURE_STORAGE_SAS_TOKEN: "{{ sunbird_public_storage_account_sas }}"
  tasks:
    - name: upload batch
      command: "oci os object bulk-upload -bn {{ plugin_container_name }} --prefix 'schemas/local/' --src-dir {{ source_name }} --overwrite"
      async: 3600
      poll: 10
